# Generated by Django 4.0.3 on 2022-04-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='news_site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.newssite'),
            preserve_default=False,
        ),
    ]
