# Generated by Django 4.0.3 on 2022-04-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_news_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.newssite'),
        ),
    ]
