# Generated by Django 4.0.3 on 2022-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newssite_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssite',
            name='relevant_section_html',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
