# Generated by Django 4.0.3 on 2022-04-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
