# Generated by Django 4.0.3 on 2022-04-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article_date_modified_article_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssite',
            name='relevant_section_html',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
