# Generated by Django 4.0.3 on 2022-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_newssite_relevant_section_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
