# Generated by Django 4.0.3 on 2022-04-11 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newsuser_groups_newsuser_user_permissions'),
        ('main', '0010_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='newssite',
            name='relevant_section_html',
        ),
        migrations.AddField(
            model_name='article',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='main.profile'),
        ),
        migrations.AddField(
            model_name='article',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes', to='main.profile'),
        ),
        migrations.AddField(
            model_name='article',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved', to='main.profile'),
        ),
    ]
