# Generated by Django 4.0.3 on 2022-04-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_article_disliked_by_remove_article_liked_by_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_like'),
        ),
    ]
