# Generated by Django 4.0.3 on 2022-04-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_like_unique_like_like_unique_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
