# Generated by Django 4.0.3 on 2022-04-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_like_like_unique_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked', to='main.profile'),
        ),
        migrations.AddField(
            model_name='article',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked', to='main.profile'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
