# Generated by Django 4.0.3 on 2022-04-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_article_disliked_by_article_liked_by_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssite',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
