# Generated by Django 4.0.3 on 2022-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_newssite_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssite',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
