# Generated by Django 4.0.3 on 2022-04-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_newssite_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssite',
            name='logo_url',
        ),
    ]
